spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/seniorcommander
    username: seniorcommander
    password: seniorcommander
  jpa:
    properties:
      hibernate:
        jdbc.time_zone: UTC

security:
  oauth2:
    client:
      clientId: hk8e73z9j2d3xplierlk0e7mgo3bw23
      clientSecret: jky4h8bo4bd471hluzmhejceg3111s0
      accessTokenUri: https://api.twitch.tv/kraken/oauth2/token
      userAuthorizationUri: https://api.twitch.tv/kraken/oauth2/authorize
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: user_read
    resource:
      userInfoUri: https://api.twitch.tv/kraken/user

pebble:
  suffix: .html

twitch:
  clientId: hk8e73z9j2d3xplierlk0e7mgo3bw23

logging.level.org.springframework.web: DEBUG
